- name: Run bot
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: python menu_bot.py
        
      - name: Upload Debug Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: debug_screen.png
